name: Build Jar Maven
on:
  workflow_call:
    inputs:
      java-version:
        description: "Java Runtime Version"
        required: false
        type: string
        default: 21
      channel-id:
        description: "Slack channel-id to post notification to"
        required: false
        type: string
        default: NO_ID

jobs:
  maven-build:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: liberica
          server-id: entur-partner
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven create jar file (without profile)
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_AUTH_USER }}
          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
        run: |
          mvn -B clean package
      - name: Upload artifact for docker deploy to fetch later.
        run: |
          mkdir libs
          mv target/app.jar libs
          echo "Artifact built and stored, ready for docker deploy step to fetch" >> $GITHUB_STEP_SUMMARY
      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: libs
          retention-days: 4
          overwrite: true
      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: "**/target/surefire-reports/"

  post-fail-to-slack-if-non-pull-request:
    needs: maven-build
    if: failure() && inputs.channel-id != 'NO_ID'
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ inputs.channel-id }}
      message: "🔴 Release build failed for ${{ github.repository }}, requested by ${{ github.actor }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

