name: maven-open-source-verify
on:
  workflow_call:
    inputs:
      java-version:
        description: Java Runtime Version
        required: true
        type: string
      commands:
        description: Maven command
        required: false
        type: string
        default: "-B clean verify --update-snapshots"

jobs:
  validate-maven-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: liberica
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Verify
        run: |
          mvn ${{ inputs.commands }}
